# Generated by Django 2.1.9 on 2019-06-17 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startup',
            name='slug',
            field=models.SlugField(help_text='A label for url config', max_length=31, unique=True),
        ),
    ]
